///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String addCard = 'assets/icons/add.svg';
  static const String addFriendlogo =
      'assets/settings_icons/add_friendlogo.svg';
  static const String anouncement = 'assets/settings_icons/anouncement.png';
  static const String appLoading = 'assets/animations/app_loading.json';
  static const String appLogo = 'assets/icons/app_logo.svg';
  static const String applePay = 'assets/icons/Apple_Pay.svg';
  static const String arrowForword = 'assets/settings_icons/arrow_forword.svg';
  static const String back = 'assets/icons/back.svg';
  static const String backArrow = 'assets/settings_icons/back_arrow.svg';
  static const String badgeLogo = 'assets/icons/badge_logo.png';
  static const String badgeSelected =
      'assets/settings_icons/badge_selected.png';
  static const String badgeSmall = 'assets/settings_icons/badge_small.png';
  static const String buttonLoader = 'assets/animations/button_loader.json';
  static const String google = 'assets/icons/google.svg';
  static const String calendar = 'assets/icons/calendar.svg';
  static const String calendarLogo = 'assets/icons/calendar_logo.svg';
  static const String call = 'assets/icons/call.svg';
  static const String fb = 'assets/icons/fb.svg';
  static const String cardLogo = 'assets/icons/card_logo.svg';
  static const String cardSelected = 'assets/icons/card_selected.svg';
  static const String cardUnselected = 'assets/icons/card_unselected.svg';
  static const String chips = 'assets/icons/chips.png';
  static const String contactMessage =
      'assets/settings_icons/contact_message.svg';
  static const String contactUs = 'assets/settings_icons/contact_us.png';
  static const String cvvLogo = 'assets/icons/cvv_logo.svg';
  static const String deleteAccount = 'assets/icons/deleted_account.svg';
  static const String electronics = 'assets/icons/electronics.svg';
  static const String email = 'assets/icons/email.svg';
  static const String global = 'assets/settings_icons/global.svg';
  static const String headphone = 'assets/settings_icons/headphone.svg';
  static const String homeSelected = 'assets/icons/home_selected.svg';
  static const String homeUnselected = 'assets/icons/home_unselected.svg';
  static const String iconSearch = 'assets/settings_icons/Icon_Search.svg';
  static const String loginBg = 'assets/images/login_bg.png';
  static const String apple = 'assets/icons/apple.svg';
  static const String infoCircle = 'assets/settings_icons/info_circle.svg';
  static const String inviteBg = 'assets/settings_icons/invite_bg.png';
  static const String locationSmall = 'assets/icons/location_small.svg';
  static const String loginImage = 'assets/icons/login_image.png';
  static const String logout = 'assets/settings_icons/logout.svg';
  static const String mapOpenLogo = 'assets/icons/map_open_logo.svg';
  static const String mapPin = 'assets/icons/map_pin.png';
  static const String notification = 'assets/icons/notification.svg';
  static const String personalcard = 'assets/settings_icons/personalcard.svg';
  static const String privacyLgo = 'assets/settings_icons/privacy_lgo.svg';
  static const String profileAdd = 'assets/settings_icons/profile_add.svg';
  static const String profileAvatar =
      'assets/settings_icons/profile_avatar.png';
  static const String profileDelete =
      'assets/settings_icons/profile_delete.svg';
  static const String refrelLogo = 'assets/icons/refrel_logo.svg';
  static const String routesLogo = 'assets/icons/routes_logo.svg';
  static const String authBg = 'assets/images/auth_bg.png';
  static const String icUser = 'assets/icons/user.svg';
  static const String searchIcon = 'assets/icons/search_icon.svg';
  static const String settingsSelected = 'assets/icons/settings_selected.svg';
  static const String settingsUnselected =
      'assets/icons/settings_unselected.svg';
  static const String shopingSelected = 'assets/icons/shoping_selected.svg';
  static const String shopingUnselected = 'assets/icons/shoping_unselected.svg';
  static const String splashBg = 'assets/icons/splash_bg.png';
  static const String splashLogo = 'assets/icons/splash_logo.svg';
  static const String startLogo = 'assets/settings_icons/start_logo.svg';
  static const String subjectLogo = 'assets/settings_icons/subject_logo.svg';
  static const String success = 'assets/icons/success.png';
  static const String termsLogo = 'assets/settings_icons/terms_logo.svg';
  static const String tickCircle = 'assets/icons/tick_circle.svg';
  static const String trofyPic = 'assets/settings_icons/trofy_pic.png';
  static const String userAvatar = 'assets/settings_icons/user_avatar.svg';
  static const String userDummy = 'assets/icons/dummy_user.svg';
  static const String userLogo = 'assets/icons/user_logo.svg';
  static const String ventCompresor = 'assets/icons/vent_compresor.svg';
  static const String ventLogo = 'assets/icons/vent_logo.svg';
  static const String verificationLogo =
      'assets/settings_icons/verification_logo.svg';
  static const String verifyImage = 'assets/icons/verify_image.png';
  static const String visaLogo = 'assets/icons/visa_logo.svg';
  static const String walletBg = 'assets/settings_icons/wallet_bg.png';
  static const String walletLogo = 'assets/settings_icons/wallet_logo.svg';
  static const String walletLogoGreen = 'assets/icons/wallet_logo_green.svg';
  static const String welcomeImage = 'assets/icons/welcome_image.svg';

  static const String introOne = 'assets/images/intro_one.svg';
  static const String introTwo = 'assets/images/intro_two.svg';
  static const String introThree = 'assets/images/intro_three.svg';

  static const String icAppBg = 'assets/images/app_bg.svg';

  static const String icAppBg2 = 'assets/images/app_bg2.png';
  static const String icLock = 'assets/icons/lock.svg';
  static const String icFbSingle = 'assets/icons/fb_single.svg';
  static const String icBackBtn = 'assets/icons/back_btn.svg';
  static const String icDummyUser = 'assets/icons/dummy_user.svg';
  static const String icGender = 'assets/icons/gender.svg';
  static const String icCake = 'assets/icons/cake.svg';
  static const String icCalender = 'assets/icons/calendar.svg';
  static const String icTask = 'assets/icons/task-square.svg';
  static const String icVip = 'assets/icons/vip.svg';
  static const String icDesignation = 'assets/icons/designation.svg';
  static const String icArrowDown = 'assets/icons/arrow_down.svg';
  static const String icDummyLogo = 'assets/icons/dummy_logo.svg';
  static const String icEye = 'assets/icons/eye.svg';
  static const String icEyeOff = 'assets/icons/eye-slash.svg';
  static const String icReferrelCode = 'assets/icons/referrel_code.svg';
  static const String icUnselectedHome = 'assets/icons/unselected_home.svg';
  static const String icUnselectedClock = 'assets/icons/unselected_clock.svg';
  static const String icUnselectedNotification =
      'assets/icons/unselected_notification.svg';
  static const String icUnselectedSetting =
      'assets/icons/unselected_setting.svg';
  static const String icSelectedClock = 'assets/icons/selected_clock.svg';
  static const String icSelectedHome = 'assets/icons/selected_home.svg';
  static const String icInvite = 'assets/icons/invite.svg';
  static const String icHomeProfile = 'assets/icons/home_profile.svg';
  static const String icSelectedNotification =
      'assets/icons/selected_notification.svg';
  static const String icSelectedSetting = 'assets/icons/selected_setting.svg';
  static const String icHomeBg = 'assets/images/home_bg.svg';
  static const String icHomePngBg = 'assets/images/home_png_bg.png';
  static const String icLocation = 'assets/icons/location.svg';
  static const String icStar = 'assets/icons/star.svg';
  static const String icMap = 'assets/icons/map.svg';
  static const String icSearch = 'assets/icons/search.svg';
  static const String icUserWhite = 'assets/icons/user_white.svg';
  static const String icProfileBg = 'assets/images/profile_bg.png';
  static const String icCloseCircle = 'assets/icons/close-circle.svg';
  static const String leftArrow = 'assets/icons/left.svg';
  static const String map = 'assets/images/map.png';
  static const String shareIcon = 'assets/icons/share_icon.svg';
  static const String searchNotication = 'assets/icons/search_notification.svg';
  static const String locationNotification =
      'assets/icons/location_notification.svg';

  // static const String icLock = 'assets/icons/lock.svg';
  static const String iconContactUs = 'assets/icons/contact_us.svg';
  static const String iconBackButton = "assets/icons/back_arrow.svg";
  static const String imsMap = "assets/icons/maps.png";
  static const String iconCheckBox = "assets/icons/checkbox.svg";
  static const String iconDelete = "assets/icons/delete.svg";
  static const String iconPerson = "assets/icons/person.svg";
  static const String iconSetRadius = "assets/icons/set_radius.svg";
  static const String iconVip = "assets/icons/vip_icon.svg";
  static const String imgVip = "assets/icons/vip.svg";
  static const String iconChangePassword = "assets/icons/change_password.svg";
  static const String iconHowItWorks = "assets/icons/how_it_works.svg";
  static const String iconArrowRight = "assets/icons/arrow_right.png";
  static const String background = "assets/images/background.png";
  static const String iconBackBtn = 'assets/icons/back.svg';
  static const String icSms = 'assets/icons/sms.svg';
  static const String icSubject = 'assets/icons/subject.svg';
  static const String icCheck = 'assets/icons/check.svg';
  static const String camera = 'assets/icons/camera.svg';
  static const String add = 'assets/icons/add_icon.svg';
  static const String checkTrue = 'assets/icons/check_true.svg';
  static const String checkFalse = 'assets/icons/check_false.svg';
  static const String icAddBtn = 'assets/icons/add_btn.svg';
  static const String icSuccess = 'assets/icons/success.svg';
  static const String bottomNav = 'assets/icons/bottom_nav.svg';
  static const String icMore = 'assets/icons/more.svg';
  static const String copy = 'assets/icons/copy.svg';
  // static const String checkFalse = 'assets/icons/check_false.svg';
  static const String reportNavClose = 'assets/icons/report_nav_close.svg';
  static const String icCopy = 'assets/icons/copy.svg';
  // static const String checkFalse = 'assets/icons/check_false.svg';
  // static const String checkFalse = 'assets/icons/check_false.svg';
  // static const String checkFalse = 'assets/icons/check_false.svg';
  // static const String checkFalse = 'assets/icons/check_false.svg';
  // static const String checkFalse = 'assets/icons/check_false.svg';
  // static const String checkFalse = 'assets/icons/check_false.svg';
  // static const String checkFalse = 'assets/icons/check_false.svg';
  // static const String checkFalse = 'assets/icons/check_false.svg';
  // static const String checkFalse = 'assets/icons/check_false.svg';
  // static const String checkFalse = 'assets/icons/check_false.svg';
  // static const String checkFalse = 'assets/icons/check_false.svg';
  // static const String checkFalse = 'assets/icons/check_false.svg';
  // static const String checkFalse = 'assets/icons/check_false.svg';
}
